version: "3"

services:
  server:
    environment:
      NODE_ENV: production
      PORT: 8100
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file:
      - docker.env
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "hardyleung/gelnail:latest"
    ports:
      - "8100:8100"
    volumes:
      - ./uploads:/usr/app/uploads
  db:
    image: "postgres:13"
    environment:
      POSTGRES_PORT: 5432
    env_file:
      - docker.env
    ports:
      - "25432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
